docs/md/content/CHANGELOG.md
docs/md/content/CONTRIBUTING.md
docs/md/content/README.md
docs/md/go.mod

Overview of PR:
- Added a hugo module to the `docs/md` directory which can then be mounted
onto the documentation website.
- Also copied the README, CHANGELOG and CONTRIBUTING markdown files to the
`docs/md` directory and added frontmatter to those files.

(GH-291) Hugo docs initialisation

---

examples/tools/epp/Dockerfile
examples/tools/epp/content/entrypoint.ps1
examples/tools/epp/content/entrypoint.sh
examples/tools/epp/prm-config.yml

This commit adds the prm-config.yml for validating any embedded puppet files in a folder. It includes a working example of the Dockerfile that would be generated via PRM to implement this plugin.
This has been manually validated against the MOTD module, passing and returning an exit code of 0.
- Resolves #9

(GH-9) Add EPP validator tool example

---

.vscode/launch.json
cmd/get/backend.go
cmd/get/get.go
cmd/get/get_test.go
cmd/root/root.go
cmd/set/backend.go
cmd/set/puppet.go
cmd/set/set.go
cmd/set/set_test.go
internal/pkg/mock/utils.go
main.go
pkg/prm/backend.go
pkg/prm/config.go
pkg/prm/config_test.go
pkg/utils/utils.go

This PR is made up of multiple commits that:
- Implement the `prm set backend` command
- Fixes an issue with the `.prm.yml` not being instantiated by Viper (#30)
- Generates sensible default values for the Puppet Runtime and Backend, if not set
The `prm get` commands will need more thorough test coverage, which has been ticketed: #28 
Resolves: #15
Resolves: #30

(GH-15) Implement prm set|get backend

---

pkg/prm/config.go

Prior to this commit, if a config value is being set
(e.g.` prm set backend`), but the Puppet version is still unset
and using the viper default value, when the config is being written,
viper still sees an empty `semver.Version` as a non-empty value
and writes it to config as:
```yaml
puppetversion: {}
```
This causes an NPE when the `.String()` method is called on
`prm.RunningConfig.PuppetVersion`.
This commit adds a check when we load the puppet ver config value
from Viper and assigns the default puppet version if the string
returned is empty.
Resolves: #36

(GH-36) Fix NPE when puppet version unset in cfg on disk

---

pkg/prm/docker.go
pkg/prm/docker_test.go

These functions are dependent on each other to the point that it makes little sense to split out

(maint) Move backends into prm package

---

acceptance/status/status_test.go
cmd/status/status.go
go.mod
go.sum
internal/pkg/mock/backend.go
main.go
pkg/prm/backend.go
pkg/prm/docker.go
pkg/prm/status.go
pkg/prm/status_test.go

This PR implements the status command. In this first pass, the logic for determining and formatting status lives in the status command package due to a cyclical dependency error caused by requiring a backend package from within the PRM package.
A future commit will need to resolve this cyclical dependency if the helper functions for status are to be moved out of the status command function as per standard design in the project. This will also be necessary for ensuring the exec and validate commands can be called without similarly needing to place the helper functions in their respective command packages.
This first pass does not yet include flags and should be updated to do so prior to any refactoring.

(GH-14) Initial status implementation

---

cmd/exec/exec.go
go.mod
go.sum
internal/pkg/mock/backend.go
internal/pkg/mock/docker.go
pkg/prm/backend.go
pkg/prm/docker.go
pkg/prm/docker_test.go
pkg/prm/exec.go
pkg/prm/prm.go
pkg/prm/prm_test.go
pkg/prm/tool.go
pkg/prm/tool_groups.go

This PR enables the PRM functionality that allows a GEM tool to be executed using the Docker backend.
When run will look in the current working directory for a validate.yml. It wil then execute against all these tools.
This needs removed from the `prm exec` exec and only used in `prm validate`. However it demonstrates the functionaliy.
```
dist\prm_windows_amd64\prm.exe exec
```
This command will look in the tools directory for a config that matches `puppetlabs/rubocop`. 
```
dist\prm_windows_amd64\prm.exe exec puppetlabs/rubocop
```
If found it will:
- parse the config into the data structure
- check if docker has an image that matches a unique name made up of the author, id, version of the tool and the user configured puppet version
- if no image is present it will generate dockerfile …

Docker backend for Gems

---

pkg/prm/docker.go

This fixes an issue were CMD was receiving multiple values in the wrong format.

(maint) Build CMD properly

---

pkg/prm/docker.go
pkg/prm/exec.go

Surfaces the exit codes and errors raised by the tool within the container, up to the main application. This affects the exit status of the `exec` command.

(GH-61) Handle tool exit codes

---

.gitignore
README.md
docs.ps1
docs.sh

Overview of PR:
- `docs.sh` and `docs.ps1` scripts created to locally host and view
changes made to PRM documentation in the `docs/md/content` directory.
- Added information pertaining to the local installation of the docs site to the `README.md`.
- Added `docs/site` to .gitignore to prevent local site installation being visible to git.
Resolves: #75

(GH-75) Created docs site scripts

---

pkg/prm/prm.go

Overview of PR:
- Added a logging message telling the user to reference the `prm exec help` help
section.
Resolves: #51

(GH-51) Improve `prm exec` error

---

cmd/exec/exec.go
cmd/status/status.go
pkg/prm/docker.go

Overview of PR:
- Removed usage of the os/io packages in the docker backend where
appropriate and replaced it with the Afero package while keeping it
functionally identical.

(GH-53) Leverage Afero instead of os/io directly

---

cmd/exec/exec.go
cmd/status/status.go
pkg/prm/config.go
pkg/prm/docker.go

Flag has been integrated into the prm config and possesses a default value.
Value of the flag is now passed through to `docker.go` where it is correctly implemented.
Acceptance test's added to prove that the timeout functions correctly.
`status.go` updated so that default timeout value is passed through, needed due to code shared between it and `exec.go`.

(GH-54) - Implement a timeout flag

---

acceptance/explain/explain_test.go

Added test's covering the following use cases:
- with no args
- output set to json
- filter by tag
- filter by category
- displaying a single topic

(GH-101) - Add acceptance tests for explain command

---

cmd/root/root.go

Ignores a gosec warning about using a string variable to define a filepath for creating a file. The file to be created is the PRM config yaml and it's filepath needs to be defined in a variable.

(MAINT) Ignore gosec warning

---

docs/md/content/explain-subsystem.md

This commit adds narrative documentation for using the explain subsystem; it covers:
- what the subsystem is/is for,
- what categories of docs can be surfaced in it,
- how to read reference docs not available in it,
- how to search for topics to read,
- how to display  a specific topic,
- and how the docs are versioned.
Resolves #97.

(GH-97) Document explain subsystem

---

docs/md/content/usage/_index.md
docs/md/content/usage/tool_installation.md

Added an installing tools page which documents the usage of the `prm install` command to install tools. Additionally, this page instructs users on how to update their tools and list installed tools in a tabular format.
There is currently no functionality to actually update tools so users are instructed to install the latest version of a tool. Tool version selection is a feature that should be added to PRM in a later version.
Resolves #95

(GH-95) Add installing and updating tools docs

---

.gitignore

This commit adds the template dir to gitignore so that goreleaser will build without error.

(MAINT) Ignore template dir

---

internal/pkg/config_processor/config_processor.go
internal/pkg/config_processor/config_processor_test.go

Make the private `config_processor` package a valid implementation of the
`ConfigProcessorI` interface in `pdkgo/pkg/config_processor` by adding the
`CheckConfig()` function.

(GH-341) Update private `config_processor`

---

cmd/validate/validate.go
cmd/validate/validate_test.go
main.go

This PR adds the validate command to the app. In this initial implementation it does not run any tools. It can list available tools but does not filter for validators only. If a tool is specified it will check to see if the tool is available.
Future work will be required to wire this up for validation functionality. This PR leaves commented code borrowed from the implementation of exec which may be useful, but must be addressed prior to release.
Resolves #7

(GH-7) Add stubbed validate command

---

cmd/validate/validate.go
internal/pkg/mock/backend.go
internal/pkg/mock/docker.go
pkg/prm/backend.go
pkg/prm/docker.go
pkg/prm/docker_test.go
pkg/prm/validate.go
pkg/prm/validate_test.go

This PR minimally implements the `prm validate` command for the docker
backend.
This PR adds unit tests for the `pkg/prm/validate.go` and
`cmd/validate/validate.go` files and for the `validate()`
function, in the `pkg/prm/docker.go` file. Mock files have
been modified appropriately to facilitate these unit tests.
This PR resolves issue #127.

(GH-127) Minimally implement docker validate

---

cmd/validate/validate.go
cmd/validate/validate_test.go
internal/pkg/mock/backend.go
internal/pkg/mock/docker.go
pkg/prm/backend.go
pkg/prm/docker.go
pkg/prm/docker_test.go
pkg/prm/validate.go
pkg/prm/validate_test.go

In this PR:
- PASS or FAIL is logged after a tool validates, depending on what code the tool exits with.
- Added a flag `--resultsView` which allows for the container logs of a docker container to either be outputted to the terminal or a file. By default for single tools, results will be outputted to the terminal.
- Added unit tests for outputting container logs to a file.
- Fixed previous unit tests for the validate command.

(GH-129) Tool output handling

---

acceptance/exec/exec_tool_common_params_test.go
acceptance/validate/validate_test.go
pkg/prm/docker.go
pkg/prm/validate.go

This commit changes how errors are outputted to the terminal.
Previously, when a tool returned a non-success exit code and no stderr,
the terminal would just output an exit code. Now, when tool returns a
non-success exit code and no stderr, the stdout will be outputted to the
terminal. The tool's stdout should contain what validation errors occurred.
Before:
```bash
5:00PM INF Validating with the metadata-json-lint tool
5:00PM ERR metadata-json-lint:
Tool exited with code: 1
TOOL NAME      | VALIDATION EXIT CODE
---------------------+-----------------------
metadata-json-lint |                    1
5:00PM ERR Validation returned 1 error
```
After:
```bash
5:01PM INF Validating with the metadata-json-lint tool
5:01PM ERR metadata-json-lint:
(ERROR) required_fields: The file did not contain …
```

(MAINT) Better error outputting to terminal

---

go.mod
go.sum

Fixes the security vulnerability described in this [issue](https://github.com/puppetlabs/prm/issues/184)

(GH-184) Fix containerd CRI plugin
